### ISSUE TITLE
Update documentation to call out branch of cc-oci-runtime this is compatible with

### ISSUE THREAD

**Issue by mcastelino** [clearcontainers/vpp#2]
Update documentation to call out branch of cc-oci-runtime this is compatible with.
The mainline cc-oci-runtime does not support VPP.

**Comment by egernst** [comment]
See https://github.com/clearcontainers/vpp/pull/3

**Comment by mcastelino** [comment]
@egernst can we move this to a branch on cc-oci-runtime itself?

**Comment by egernst** [comment]
Yes, but I don't have such permissions to do so.  Can we wait to update documentation first?
